### ISSUE TITLE
注入后没有在127.0.0.1:19088启动服务，而在0.0.0.0:19088启动服务，怎么回事？也无法调用

### ISSUE THREAD

**Issue by linrun** [ttttupup/wxhelper#121]
"D:\Program Files\Python310\python.exe" C:\Users\Administrator\PycharmProjects\okx\client.py 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\okx\client.py", line 521, in <module>
    send_text()
  File "C:\Users\Administrator\PycharmProjects\okx\client.py", line 38, in send_text
    response = requests.request("POST", url, headers=headers, data=payload)
  File "D:\Program Files\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\Python310\lib\site-packages\requests\sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)
  File "D:\Program Files\Python310\lib\site-packages\requests\sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '127.0.0.1:19088/api/?type=2'

Process finished with exit code 1

**Comment by lanlandexiaolan** [comment]
0.0.0.0:19088  包括127.0.0.1 也包括你的局域网地址

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/discussions/65
